# Generated by Django 2.0.4 on 2018-05-16 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starpick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='tag',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pick_tag', to='starpick.Tag'),
        ),
    ]
