# Generated by Django 2.0.4 on 2018-05-16 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starpick', '0002_auto_20180516_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='tag',
        ),
        migrations.AlterField(
            model_name='tag',
            name='pick',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='starpick.Pick'),
        ),
    ]
