# Generated by Django 2.0.4 on 2018-05-30 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starpick', '0005_auto_20180524_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='starpick.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='starpick.User')),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
