# Generated by Django 2.0.4 on 2018-06-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starpick', '0006_auto_20180530_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likenumber',
            field=models.IntegerField(default=0),
        ),
    ]
