# Generated by Django 2.0.4 on 2018-06-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starpick', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='commentnumber',
            field=models.IntegerField(default=0),
        ),
    ]
