# Generated by Django 2.0.4 on 2018-06-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starpick', '0009_entry_commentnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashName', models.CharField(max_length=30)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagHashes', to='starpick.Entry')),
            ],
        ),
        migrations.AlterField(
            model_name='pick',
            name='brand',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='pick',
            name='category',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='pick',
            name='idolName',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='pick',
            name='officialLink',
            field=models.URLField(default='none'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='pic',
            field=models.URLField(default='http://none.none'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='price',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='pick',
            name='size',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
