# Generated by Django 2.0.4 on 2018-06-29 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starpick', '0010_auto_20180626_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='dissnumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diss',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diss', to='starpick.Entry'),
        ),
        migrations.AddField(
            model_name='diss',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diss', to='starpick.User'),
        ),
    ]
